//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.22 at 03:39:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.digitPa.gov.it/protocollo/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.axiastudio.suite.interoperabilita.entities.xsd;
