INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (1, 'A', 'AUSTRIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (2, 'AAA', 'APOLIDE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (3, 'ABU', 'EMIRATO DI ABU-DHABI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (4, 'ADN', 'YEMEN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (5, 'AED', 'DIRHAM EMIRATI ARABI UNITI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (6, 'AFG', 'AFGHANISTAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (7, 'AL', 'ALBANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (8, 'AND', 'ANDORRA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (9, 'AUS', 'AUSTRALIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (10, 'B', 'BELGIO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (11, 'BD', 'BANGLADESH');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (12, 'BDS', 'BARBADOS');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (13, 'BG', 'BULGARIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (14, 'BH', 'HONDURAS BRITANNICO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (15, 'BIH', 'BOSNIA-ERZEGOVINA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (16, 'BL', 'BASUTOLAND');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (17, 'BOS', 'BOSNIA-ERZEGOVINA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (18, 'BP', 'BOTSWANA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (19, 'BR', 'BRASILE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (20, 'BRG', 'GUIANA BRITANNICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (21, 'BRM', 'ISOLE BERMUDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (22, 'BRN', 'BAHREIN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (23, 'BRU', 'BRUNEI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (24, 'BS', 'BAHAMA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (25, 'BUR', 'BIRMANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (26, 'C', 'CUBA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (27, 'CDN', 'CANADA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (28, 'CH', 'SVIZZERA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (29, 'CI', 'COSTA DI AVORIO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (30, 'CK', 'REPUBBLICA CECA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (31, 'CL', 'CEYLON');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (32, 'CNB', 'BORNEO DEL NORD');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (33, 'CO', 'COLOMBIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (34, 'CR', 'COSTA RICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (35, 'CRO', 'CROAZIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (36, 'CS', 'CECOSLOVACCHIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (37, 'CSI', 'RUSSIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (38, 'CV', 'ISOLA DI CAPO VERDE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (39, 'D', 'GERMANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (40, 'DDR', 'REPUBBLICA DEMOCRATICA DI GERMANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (41, 'DK', 'DANIMARCA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (42, 'DY', 'DAHOMEY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (43, 'DZ', 'ALGERIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (44, 'E', 'SPAGNA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (45, 'EAK', 'KENYA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (46, 'EAT', 'TANZANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (47, 'EAU', 'UGANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (48, 'EC', 'ECUADOR');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (49, 'EIR', 'IRLANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (50, 'ER', 'ERITREA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (51, 'EST', 'ESTONIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (52, 'ET', 'EGITTO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (53, 'ETH', 'ETIOPIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (54, 'F', 'FRANCIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (55, 'FI', 'FILIPPINE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (56, 'FJI', 'ISOLE FIJI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (57, 'FL', 'LIECHTENSTEIN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (58, 'G', 'GUATEMALA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (59, 'GAB', 'REP. DEL GABON');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (60, 'GB', 'GRAN BRETAGNA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (61, 'GBA', 'ISOLE ALDERNEY-AUVIGNY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (62, 'GBG', 'ISOLA GUERNSEY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (63, 'GBJ', 'ISOLA DI JERSEY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (64, 'GBM', 'ISOLA DI MAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (65, 'GBY', 'ISOLA DI MALTA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (66, 'GBZ', 'GIBILTERRA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (67, 'GEO', 'GEORGIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (68, 'GH', 'GHANA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (69, 'GR', 'GRECIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (70, 'GV', 'GUINEA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (71, 'H', 'UNGHERIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (72, 'HK', 'HONG-KONG');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (73, 'HN', 'HONDURAS');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (74, 'HV', 'ALTO VOLTA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (75, 'IL', 'ISRAELE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (76, 'IND', 'INDIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (77, 'IR', 'IRAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (78, 'IRQ', 'IRAQ');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (79, 'IS', 'ISLANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (80, 'IT', 'ITALIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (81, 'J', 'GIAPPONE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (82, 'JA', 'GIAMAICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (83, 'JOR', 'GIORDANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (84, 'K', 'CAMBOGIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (85, 'KL', 'LIBIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (86, 'KWT', 'KUWAIT');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (87, 'KZ', 'KAZACHISTAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (88, 'L', 'LUSSEMBURGO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (89, 'LAO', 'LAOS');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (90, 'LET', 'LETTONIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (91, 'LIB', 'LIBERIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (92, 'LIT', 'LITUANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (93, 'LRD', 'DOLLARO LIBERIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (94, 'LS', 'LESOTO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (95, 'M', 'MALTA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (96, 'MA', 'MAROCCO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (97, 'MAC', 'MACEDONIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (98, 'MAU', 'MAURITANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (99, 'MC', 'MONACO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (100, 'MEX', 'MESSICO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (101, 'MOC', 'MOZAMBICO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (102, 'MOL', 'MOLDOVA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (103, 'MS', 'MAURIZIO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (104, 'MT', 'TANGERI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (105, 'N', 'NORVEGIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (106, 'NA', 'ANTILLE OLANDESI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (107, 'NEP', 'NEPAL');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (108, 'NF', 'TERRANOVA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (109, 'NGN', 'GUINEA OLANDESE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (110, 'NIC', 'NICARAGUA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (111, 'NIG', 'NIGER');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (112, 'NL', 'OLANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (113, 'NZ', 'NUOVA ZELANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (114, 'OMA', 'SULTANATO DELL''OMAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (115, 'P', 'PORTOGALLO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (116, 'PA', 'PANAMA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (117, 'PAK', 'PAKISTAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (118, 'PAN', 'ANGOLA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (119, 'PE', 'PERU');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (120, 'PL', 'POLONIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (121, 'PTM', 'MALAYSIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (122, 'PY', 'PARAGUAY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (123, 'QAT', 'QATAR');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (124, 'R', 'ROMANIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (125, 'RA', 'ARGENTINA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (126, 'RB', 'BOLIVIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (127, 'RBE', 'REPUBBLICA DEL BENIN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (128, 'RC', 'CINA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (129, 'RCA', 'REP. CENTRO AFRICANA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (130, 'RCB', 'CONGO OVEST');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (131, 'RCF', 'FORMOSA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (132, 'RCH', 'CILE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (133, 'RCL', 'CONGO EST');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (134, 'RD', 'DOMINICANA REPUBBLICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (135, 'RH', 'HAITI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (136, 'RI', 'INDONESIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (137, 'RL', 'LIBANO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (138, 'RM', 'REP. MALGASCIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (139, 'RMM', 'MALI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (140, 'RNR', 'ZAMBIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (141, 'RNY', 'MALAWI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (142, 'ROK', 'KOREA DEL SUD');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (143, 'RSA', 'REPUBBLICA DI SUDAFRICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (144, 'RSM', 'SAN MARINO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (145, 'RSR', 'RHODESIA DEL SUD');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (146, 'RU', 'BURUNDI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (147, 'RWA', 'RUANDA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (148, 'RY', 'CIPRO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (149, 'S', 'SVEZIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (150, 'SA', 'ARABIA SAUDITA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (151, 'SAL', 'EL SALVADOR');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (152, 'SCV', 'VATICANO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (153, 'SD', 'SWAZILAND');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (154, 'SER', 'SERBIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (155, 'SF', 'FINLANDIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (156, 'SGP', 'SINGAPORE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (157, 'SK', 'SARAWAK');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (158, 'SLK', 'SRI LANKA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (159, 'SLO', 'SLOVENIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (160, 'SLV', 'SLOVACCHIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (161, 'SME', 'SURINAME');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (162, 'SN', 'SENEGAL');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (163, 'SNE', 'GUIANA OLANDESE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (164, 'SOM', 'SOMALIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (165, 'SU', 'URSS');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (166, 'SUD', 'SUDAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (167, 'SWA', 'AFRICA DEL SUD OVEST');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (168, 'SY', 'SEYCEL');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (169, 'SYR', 'SIRIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (170, 'T', 'TAILANDIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (171, 'TC', 'CAMERUN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (172, 'TCH', 'CIAD');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (173, 'TG', 'TOGO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (174, 'TN', 'TUNISIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (175, 'TR', 'TURCHIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (176, 'TT', 'TRINIDAD E TOBAGO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (177, 'TWA', 'TAIWAN');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (178, 'U', 'URUGUAY');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (179, 'UAE', 'EMIRATI ARABI UNITI');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (180, 'UCR', 'UCRAINA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (181, 'USA', 'STATI UNITI AMERICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (182, 'UV', 'BURKINA FASO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (183, 'VAN', 'VANUATU');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (184, 'VN', 'VIETNAM');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (185, 'WAC', 'COSTA DI ORO');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (186, 'WAG', 'GAMBIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (187, 'WAL', 'SIERRA LEONE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (188, 'WAN', 'NIGERIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (189, 'WS', 'ISOLE SAMOA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (190, 'YU', 'JUGOSLAVIA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (191, 'YV', 'VENEZUELA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (192, 'ZA', 'SUD AFRICA');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (193, 'ZI', 'ZIMBABWE');
INSERT INTO anagrafiche.stato (id, codice, descrizione) VALUES (194, 'ZRE', 'ZAIRE');
